### ISSUE TITLE
ipynb2html: command not found

### ISSUE THREAD

**Issue by bendominguez0111** [jirutka/ipynb2html#9]
Hi,

I'm trying to use your library to convert some of jupyter notebooks to html for my blog. I installed you dependency via npm but I get this error "ipynb2html: command not found" when I try to run the cli tool.

Any ideas why this is happening?

**Comment by jirutka** [comment]
What package did you install? The `ipynb2html` command is provided by package ipynb2html-cli. Try to run it as `npx ipynb2html`, for the case you don't have PATH set correctly.
